### PR TITLE
ZeroFox Threat Intelligence: Bugfix - Fix version Consistency

### PR DESCRIPTION
**Pull request by DNRRomero**
Please ensure your pull request (PR) adheres to the following guidelines:

- Please refer to our contributing documentation for any questions on submitting a pull request, link: [Contribution Guide](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONTRIBUTING.md)

#### Please check if your PR fulfills the following requirements:
- [x] Testing of all the changes has been performed (for bug fixes / features)
- [x] The manual_readme_content.md has been reviewed and added / updated if needed (for bug fixes / features)
- [x] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [ ] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [ ] Verify all checks are passing.
- [ ] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [ ] Do NOT submit updates to dependencies unless it fixes an issue.
#### Please check the type of change your PR introduces:
- [ ] New App
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation
- [ ] Other (please describe):

## Security Considerations (REQUIRED)
- [ ] If you are exposing any endpoints using a [REST handler](https://docs.splunk.com/Documentation/SOAR/current/DevelopApps/RESTHandlers),
  please document them in the `manual_readme_content.md`.
- [ ] If this is a new connector or you are adding new actions
    - [ ] Please document in the `manual_readme_content.md` all methods (eg, OAuth) used to authenticate
      with the service that the connector is integrating with.
    - [ ] If any actions are unable to run on SOAR Cloud, please document this in the `manual_readme_content.md`.
- [ ] Are you introducing any new cryptography modules? If yes, please elaborate their purpose:
- [ ] Are you are accessing the file system? If yes, please verify that you are only accessing paths returned through
the [Vault](https://docs.splunk.com/Documentation/SOARonprem/5.2.1/DevelopApps/AppDevAPIRef#Vault) API.
- [ ] Are you are marking code to be ignored by Semgrep with [`nosemgrep`](https://semgrep.dev/docs/ignoring-files-folders-code/#ignoring-code-through-nosemgrep)?
If yes, please provide justification in an additional comment next to the ignored code.

## Release Notes (REQUIRED)
- Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.

## What is the current behavior? (OPTIONAL)
- Describe the current behavior that you are modifying.

## What is the new behavior? (OPTIONAL)
- Describe the behavior or changes that are being added by this PR.

## Other information (OPTIONAL)
- Any other information that is important to this PR such as screenshots of how the component looks before and after the change.

## Pay close attention to (OPTIONAL)
- Any specific code change or test case points which must be addressed/reviewed at the time of GA release.

## Screenshots (if relevant)

---
Thanks for contributing!

### CODE REVIEW

**Comment by spopat-crest** [comment]
Hello @DNRRomero, Downgrading the app version from 1.1.0 to 1.0.1 will confuse the existing customers as next release version can not be lower than the previous release. We will proceed with bug fix and the released version can either be 1.2.0 or 1.1.1 whichever sounds good to you.

As a best practice we would recommend not to downgrade app version.

cc: @nastorSplunk @junlinl-splunk @ishans-crest

**Comment by dnrr-dev** [comment]
Hi @spopat-crest
As with our ZeroFox Alerts app, the reason for the version-update change is that there is an existing manually distributed version of this app that has version 1.0.1, and customers are already confused about the Splunkbase app being 1.0.0
There are no customers we know about using the Splunkbase version of our app.
Now, we have no problem in changing this to 1.1.1 if that allows us to make the changes to our app

**Comment by mishalp-crest** [comment]
@DNRRomero Can you update the release notes and give me write access?

**Comment by dnrr-dev** [comment]
Hi @mishalp-crest  I've just updated the release notes. Regarding write access, do you mean write access in our forked repository?
Why is that required?

**Comment by mishalp-crest** [comment]
@DNRRomero Yes, to do cosmetic standard dev check changes if needed
Also, add the note in unreleased.md

**Comment by dnrr-dev** [comment]
Hi @mishalp-crest, I moved release notes to unreleased, and also gave you write-access

**Comment by mishalp-crest** [comment]
@DNRRomero I have made some changes 
let me know if you have any concerns

**Comment by dnrr-dev** [comment]
@mishalp-crest looks good to me

**Comment by mishalp-crest** [comment]
@DNRRomero Do you want to keep the 1.1.1 version for this app as we are doing for zerofoxalerts?

**Comment by dnrr-dev** [comment]
@mishalp-crest only the 1.1.1 version of this app should show up in splunkbase

**Review by dhwanis-crest — APPROVED** [review]

**Pull request merged**
